version: 2
updates:
  - package-ecosystem: github-actions
    directory: ".github"
    schedule:
      interval: daily
      timezone: "Europe/London"
    open-pull-requests-limit: 10
  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: daily
      timezone: "Europe/London"
    open-pull-requests-limit: 10
    groups:
      xunit:
        patterns:
          - "xunit*"
