namespace ArgumentativeFilters.Generator.CodeGeneration;

public static class CodeSnippets
{
    public static string ArgumentativeFilterFileHeader => $@"// <auto-generated/>
using global::System;
using global::System.Linq;
using global::Microsoft.Extensions.DependencyInjection;

#nullable enable

";
}